segal-gicp:
  type: Article
  title: Generalized-ICP
  author:
  - Segal, Aleksandr V.
  - Hähnel, Dirk
  - Thrun, Sebastian
  date: 2009
  url: https://api.semanticscholar.org/CorpusID:231748613
  parent:
    type: proceedings
    title: 'Robotics: Science and Systems'

icp-notebook:
  author: Igor Bogoslavskyi
  type: Web
  url: https://nbviewer.org/github/niosus/notebooks/blob/master/icp.ipynb
  date: 2021


point-to-plane-icp:
  type: Article
  title: Linear Least-Squares Optimization for Point-to-Plane ICP Surface Registration
  author: Kok-Lim Low
  url: https://www.comp.nus.edu.sg/~lowkl/publications/lowk_point-to-plane_icp_techrep.pdf
  date: 2004

IDAPILecture14:
  type: Web
  title: Intelligent Data Analysis and Probabilistic Inference Lecture 14
  date: 2018
  url: https://www.doc.ic.ac.uk/~dfg/ProbabilisticInference/old_IDAPILecture14.pdf